---
- name: create standard home directory stuff
  file: name={{ item }} state=directory
  with_items:
      - '{{ home }}/src'

- name: Install favorite packages from homebrew
  homebrew: name={{ item }} state=present
  with_items:
    - git
    - vim
#    - bgpq3
    - tmux
    - mtr
#    - hping3
#    - tshark
    - go
    - cowsay
    - wget
    - nmap
    - mutt
    - htop
    - irssi
    - imagemagick
    - htop-osx
    - jq
    - ettercap
    - aspell
    - gnupg


- name: Install favorite packages from homebrew cask
  shell: brew cask install {{ item }}
  with_items:
    - iterm2
    - google-chrome
    - virtualbox
    - vagrant
    - sublime-text
    - transmit
    - spotify
    - adium
    - vlc
    - skype
    - hipchat

- include: python.yml
#- include: local.yml
- include: dayjob.yml
