---
- name: create standard home directory stuff
  file: name={{ item }} state=directory
  with_items:
      - '{{ home }}/src'


- include: homebrew.yml
- include: python.yml
- include: local.yml
- include: dayjob.yml
